### ISSUE TITLE
Add DPS5020 communication

### ISSUE THREAD

**Issue by CommanderRedYT** [bobbycar-graz/bobbycar-boardcomputer-firmware#281]
Using another ESP, it should be possible to communicate with the DPS charging station and manage voltage and amps, and also monitor it to show stats like charged watthours / amphours. There could also be a progress bar for how much the battery is charged.

- Only show charger menu item when charger is in reach (RSSI)
- Charging animation (#24)
- Optional: When bobbycar is in charging mode, disable stuff like driving mode and just send open mode (or mosfets off)

**Comment by peterpoetzi** [comment]
An ESP32 running a fork of the bobbycar-boardcomputer-firmware should be connected to the DPS5020 with UART and be able to:
- accumulate Wh and Ah
- send the live values over ESP-NOW
- send the live values to the UDP cloud

The ESP32 should also have a remote-control mode which can be activated or deactivated with a menu setting

Luckily, there is not much danger which can be done to the Bobbycar's battery in case the remote control does not work correctly, because we are charging at 50V / 20A anyway and it is impossible to set a higher setting on the DPS5020 ;)
