### ISSUE TITLE
Keep old menu selection when going back

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [bobbycar-graz/bobbycar-boardcomputer-firmware#9]
Menus are completely destructed when leaving, making it hard to keep the selection.
Maybe this can be evaluated at compile time, as it should be known which menu entry led to the current screen.

**Comment by CommanderRedYT** [comment]
How would you know if it was a switchscreenaction to go forwards or backwards? What if the BackAction of the menu to go into does point into a different screen? 

One solution would be to rewrite every BackAction / Button that goes into the last menu. We would need a root element and a stack where we could push / pull for example the screen class and the select-index. 
The back action would just pop the next element from the stack until the root element is reached. 

This could also fix weird issues like pressing back in "Mode settings" screen when accessing through the main menu instead of the settings menu.
